[options]
HoldPkg     = pacman glibc
XferCommand = /usr/bin/curl -L -C - -f -o %o %u
# curl is good too
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# temp removal
# deal with it losers. im r2 for this shit
# this os is designed for x86_64 only so why not change it to that

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
